adding report on linting

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -12,13 +12,20 @@ echo "🔍 Running pre-push hook"
 echo "🔄 Running tests..."
 yarn test
 
+if [ $? -eq 0 ]; then
+  echo -e "${GREEN}✅ Tests passed${NC}"
+else
+  echo -e "${RED}❌ Tests failed${NC}"
+  exit 1
+fi
+
 # Running yarn lint
 echo "🔄 Running yarn lint..."
 yarn lint
 
 if [ $? -eq 0 ]; then
-  echo -e "${GREEN}✅ Tests passed${NC}"
+  echo -e "${GREEN}✅ Yarn lint passed${NC}"
 else
-  echo -e "${RED}❌ Tests failed${NC}"
+  echo -e "${RED}❌ Yarn lint failed${NC}"
   exit 1
 fi
